replicaCount: 2

image:
  repository: ozharkov/cicd-prod   # ← заменить!
  pullPolicy: IfNotPresent
  tag: "3cb9250"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30081

# OTel и app переменные окружения
env:
  - name: APP_VERSION
    value: "1.0.0"
  - name: OTEL_SERVICE_NAME
    value: "cicd-prod"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "otel-collector-opentelemetry-collector:4317"
  - name: ENVIRONMENT
    value: "production"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Разделяем liveness и readiness — продакшн best practice
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

# Плавное обновление без даунтайма
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
