replicaCount: 2

image:
  repository: YOUR_DOCKERHUB_USERNAME/cicd-demo
  pullPolicy: IfNotPresent
  tag: "b360bf4"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

# OTel переменные окружения для приложения
env:
  - name: APP_VERSION
    value: "2.0.0"
  - name: OTEL_SERVICE_NAME
    value: "cicd-demo"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector:4317"
  - name: ENVIRONMENT
    value: "production"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
