apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: "0.104.0"
    helm:
      valueFiles: []
      values: |
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: "0.104.0"
        ports:
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false
        config:
          receivers:
            jaeger: null
            prometheus: null
            zipkin: null
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"
          processors:
            batch:
              timeout: 1s
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
          exporters:
            debug:
              verbosity: normal
            otlp/jaeger:
              endpoint: "jaeger:4317"
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/jaeger, debug]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [debug]
              logs: null
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
