apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OleksandrZharkov/cicd-prod   # ← заменить!
    targetRevision: HEAD
    path: helm/cicd-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
